apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

helmCharts:
- name: influxdb
  releaseName: azure-marketplace
  repo: https://marketplace.azurecr.io/helm/v1/repo # https://bitnami.com/stack/influxdb/helm
  version: 2.6.1
  valuesFile: values.yaml
