apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: operators

helmCharts:
- name: grafana-agent-operator
  releaseName: grafana-agent-operator
  repo: https://grafana.github.io/helm-charts
  version: "0.2.12"

resources:
- https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.grafana.com_grafanaagents.yaml
- https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.grafana.com_podlogs.yaml
- https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.grafana.com_logsinstances.yaml
