apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

helmCharts:
- name: redis
  releaseName: redis
  repo: https://charts.bitnami.com/bitnami
  version: 14.8.11
  valuesFile: values.yaml
  namespace: default
