sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-operated.default.svc.cluster.local:9090