apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telegraf
  namespace: argocd
spec:
  project: default
  source:
    chart: influxdata
    repoURL: https://helm.influxdata.com/
    targetRevision: 1.8.26
    helm:
      values: |
        replicaCount: 2
        image:
          repository: quay.io/influxdb/telegraf-operator
          pullPolicy: IfNotPresent
          sidecarImage: "docker.io/library/telegraf:1.22"

        classes:
          data:
            default: |
              [[outputs.influxdb]]
                urls = ["http://influxdb:8086"]
                database = "testground"

        certManager:
          enable: false

        imagePullSecrets: []
        nameOverride: ""
        fullnameOverride: ""
        serviceAccount:
          # Annotations to add to the service account
          annotations: {}
        podSecurityContext: {}
          # fsGroup: 2000
        securityContext: {}
          # capabilities:
          #   drop:
          #   - ALL
          # readOnlyRootFilesystem: true
          # runAsNonRoot: true
          # runAsUser: 1000
        resources:
          limits:
            cpu: 400m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
        nodeSelector: {}
        tolerations: []
        affinity: {}
        requireAnnotationsForSecret: false
        # allow hot reload ; disabled by default to support versions of telegraf
        # that do not support hot-reload and --watch-config flag
        hotReload: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
