apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efs
spec:
  project: default
  source:
    repoURL: https://github.com/celestiaorg/testground-infra.git
    revision: jose/hackground-k8s-tf
    path: 'kustomize/efs'
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
