apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespace: argocd
spec:
  project: default
  source:
    chart: celestiaorg/influxdb
    repoURL: ghcr.io
    targetRevision: 2.6.1
    helm:
      valueFiles:
      - "../helm/influxdb/values.yml"
      releaseName: influxdb
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
