apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- aws-applicationset.yaml
- kustomization.yaml
- observability-applicationset.yaml
- testground-applicationset.yaml
- influxdb.yaml
- networking-applicationset.yaml
- telegraf-operator.yaml
