#apiVersion: argoproj.io/v1alpha1
#kind: ApplicationSet
#metadata:
#  name: networking
#  namespace: argocd
#spec:
#  generators:
#  - git:
#      repoURL: https://github.com/celestiaorg/testground-infra.git
#      revision: jose/hackground-k8s-tf
#      directories:
#      - path: 'manifests/networking/*'
#      - path: manifests/networking/deactivated
#        exclude: true
#  template:
#    metadata:
#      name: 'networking-{{path[2]}}'
#    spec:
#      project: default
#      source:
#        repoURL: https://github.com/celestiaorg/testground-infra.git
#        path: 'manifests/networking/{{path[2]}}'
#        targetRevision: jose/hackground-k8s-tf
#      destination:
#        name: in-cluster
#        namespace: default
#      syncPolicy:
#        automated:
#          prune: true
#          allowEmpty: true
#          selfHeal: true
#        syncOptions:
#        - ApplyOutOfSyncOnly=true
#        - CreateNamespace=true
