apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telegraf-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: telegraf-operator
    repoURL: https://helm.influxdata.com/
    targetRevision: 1.3.11
    helm:
      valueFiles:
      - "../helm/telegraf-operator/values.yml"
      releaseName: telegraf-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
