apiVersion: v1
kind: Service
metadata:
  name: testground-daemon
  labels:
    app: testground-daemon
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8042
  selector:
    app: testground-daemon