apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: influxdb
  releaseName: influxdb
  repo: https://charts.bitnami.com/bitnami
  version: "2.7.0"
  valuesFile: values.yaml
