apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: celestiaorg/influxdb
  releaseName: influxdb
  repo: https://ghcr.io/v2/celestiaorg/influxdb/
  version: 2.6.1
  valuesFile: values.yaml
