apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: celestiaorg/influxdb
  releaseName: influxdb
  repo: oci://ghcr.io/celestiaorg/charts
  version: 2.6.1
  valuesFile: values.yaml
